## Bag of Words Lab

In [11]:
import pandas as pd
import os
import numpy as np

### let's define the docs array that contains the paths of doc1.txt, doc2.txt, and doc3.txt.

### We need to create a BoW from a list of documents. The documents (doc1.txt, doc2.txt, and doc3.txt) can be found in the your-code directory of this exercise. You will read the content of each document into an array of strings named corpus.
### Now let's define the docs array that contains the paths of doc1.txt, doc2.txt, and doc3.txt.

In [10]:
docs=[]
for filename in os.listdir('./'):
    if filename.endswith('.txt'):
        docs.append(filename)
print(docs)

['doc1.txt', 'doc3.txt', 'doc2.txt']


### Define an empty array corpus that will contain the content strings of the docs. Loop docs and read the content of each doc into the corpus array.

In [12]:

corpus=[]

for Filename in os.listdir('./'):
    if Filename.endswith('.txt'):
        with open(Filename,'r') as f:
            content=f.readline()
        corpus.append(content)
print(corpus)

['Ironhack is cool.', 'I am a student at Ironhack.', 'I love Ironhack.']


### Print corpus.

In [186]:
print(corpus)

['Ironhack is cool.', 'I am a student at Ironhack.', 'I love Ironhack.']


### Write your code below to process corpus (convert to lower case and remove special characters).

In [79]:
corpus_clean=[(lambda i: i.lower().strip('\.')) (i) for i in corpus] 
print(corpus_clean)

['ironhack is cool', 'i am a student at ironhack', 'i love ironhack']


### Now define bag_of_words as an empty array. It will be used to store the unique terms in corpus.

In [81]:
bag_of_words=[]

### Loop through corpus. In each loop, do the following: 
### 1. Break the string into an array of terms. 
### 2. Create a sub-loop to iterate the terms array. In each sub-loop, you'll check if the current term is already contained in bag_of_words. If not in bag_of_words, append it to the array.

In [134]:


for i in corpus_clean:
    terms = i.split(' ')
    for word in terms:
        if word not in bag_of_words:
            bag_of_words.append(word)
            
            
print(bag_of_words)

['ironhack', 'is', 'cool', 'i', 'am', 'a', 'student', 'at', 'love']


### Now we define an empty array called term_freq. Loop corpus for a second time. In each loop, create a sub-loop to iterate the terms in bag_of_words. 
### Count how many times each term appears in each doc of corpus. Append the term-frequency array to term_freq.

In [164]:



term_freq=[]

count=0
    
for i in corpus_clean:
    tf=[] #porqué hay una diferencia si declaro dentro de aquí?
    count=0 
    for j in bag_of_words:
        if j in i:
            tf.append(count+1) #como hacerle si quiero que count se vaya aumentando pero quiero que regrese a 0 despues de cada iteración de i
        else:
            tf.append(0)
    
    term_freq.append(tf)

print(term_freq)


[[1, 1, 1, 1, 0, 1, 0, 0, 0], [1, 0, 0, 1, 1, 1, 1, 1, 0], [1, 0, 0, 1, 0, 1, 0, 0, 1]]


In [173]:
term_freq2=[]
corpus_split=[]

for i in corpus_clean:
    corpus_split.append(i.split(' '))
print(corpus_split)

for x in corpus_split:
    tf2=[]
    
    for y in bag_of_words:
        #count=0 
        if y in x:
            tf2.append(1)
        else:
            tf2.append(0)
    term_freq2.append(tf2)
            
print(term_freq2)


[['ironhack', 'is', 'cool'], ['i', 'am', 'a', 'student', 'at', 'ironhack'], ['i', 'love', 'ironhack']]
[[1, 1, 1, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 1, 1, 1, 1, 0], [1, 0, 0, 1, 0, 0, 0, 0, 1]]


In [121]:
[1, 1, 1, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 1, 0, 0, 0, 0], [1, 0, 0, 1, 0, 1, 1, 1, 1]



([1, 1, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 1, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 1, 1, 1, 1])

## Bonus Question


### Optimize your solution for the above question by removing stop words from the BoW. For your convenience, a list of stop words is defined for you in the next cell.

### Requirements:

### Combine all your previous codes to the cell below. Improve your solution by ignoring stop words in bag_of_words.


In [175]:
stop_words = ['all', 'six', 'less', 'being', 'indeed', 'over', 'move', 'anyway', 'fifty', 'four', 'not', 'own', 'through', 'yourselves', 'go', 'where', 'mill', 'only', 'find', 'before', 'one', 'whose', 'system', 'how', 'somewhere', 'with', 'thick', 'show', 'had', 'enough', 'should', 'to', 'must', 'whom', 'seeming', 'under', 'ours', 'has', 'might', 'thereafter', 'latterly', 'do', 'them', 'his', 'around', 'than', 'get', 'very', 'de', 'none', 'cannot', 'every', 'whether', 'they', 'front', 'during', 'thus', 'now', 'him', 'nor', 'name', 'several', 'hereafter', 'always', 'who', 'cry', 'whither', 'this', 'someone', 'either', 'each', 'become', 'thereupon', 'sometime', 'side', 'two', 'therein', 'twelve', 'because', 'often', 'ten', 'our', 'eg', 'some', 'back', 'up', 'namely', 'towards', 'are', 'further', 'beyond', 'ourselves', 'yet', 'out', 'even', 'will', 'what', 'still', 'for', 'bottom', 'mine', 'since', 'please', 'forty', 'per', 'its', 'everything', 'behind', 'un', 'above', 'between', 'it', 'neither', 'seemed', 'ever', 'across', 'she', 'somehow', 'be', 'we', 'full', 'never', 'sixty', 'however', 'here', 'otherwise', 'were', 'whereupon', 'nowhere', 'although', 'found', 'alone', 're', 'along', 'fifteen', 'by', 'both', 'about', 'last', 'would', 'anything', 'via', 'many', 'could', 'thence', 'put', 'against', 'keep', 'etc', 'amount', 'became', 'ltd', 'hence', 'onto', 'or', 'con', 'among', 'already', 'co', 'afterwards', 'formerly', 'within', 'seems', 'into', 'others', 'while', 'whatever', 'except', 'down', 'hers', 'everyone', 'done', 'least', 'another', 'whoever', 'moreover', 'couldnt', 'throughout', 'anyhow', 'yourself', 'three', 'from', 'her', 'few', 'together', 'top', 'there', 'due', 'been', 'next', 'anyone', 'eleven', 'much', 'call', 'therefore', 'interest', 'then', 'thru', 'themselves', 'hundred', 'was', 'sincere', 'empty', 'more', 'himself', 'elsewhere', 'mostly', 'on', 'fire', 'am', 'becoming', 'hereby', 'amongst', 'else', 'part', 'everywhere', 'too', 'herself', 'former', 'those', 'he', 'me', 'myself', 'made', 'twenty', 'these', 'bill', 'cant', 'us', 'until', 'besides', 'nevertheless', 'below', 'anywhere', 'nine', 'can', 'of', 'your', 'toward', 'my', 'something', 'and', 'whereafter', 'whenever', 'give', 'almost', 'wherever', 'is', 'describe', 'beforehand', 'herein', 'an', 'as', 'itself', 'at', 'have', 'in', 'seem', 'whence', 'ie', 'any', 'fill', 'again', 'hasnt', 'inc', 'thereby', 'thin', 'no', 'perhaps', 'latter', 'meanwhile', 'when', 'detail', 'same', 'wherein', 'beside', 'also', 'that', 'other', 'take', 'which', 'becomes', 'you', 'if', 'nobody', 'see', 'though', 'may', 'after', 'upon', 'most', 'hereupon', 'eight', 'but', 'serious', 'nothing', 'such', 'why', 'a', 'off', 'whereby', 'third', 'i', 'whole', 'noone', 'sometimes', 'well', 'amoungst', 'yours', 'their', 'rather', 'without', 'so', 'five', 'the', 'first', 'whereas', 'once']



In [177]:
new_bow=[i for i in bag_of_words if i not in stop_words]
print(new_bow)

['ironhack', 'cool', 'student', 'love']


In [179]:
term_freq3=[]
corpus_split=[]

for i in corpus_clean:
    corpus_split.append(i.split(' '))

for x in corpus_split:
    new_tf2=[]
    
    for y in new_bow:
        #count=0 
        if y in x:
            new_tf2.append(1)
        else:
            new_tf2.append(0)
    term_freq3.append(new_tf2)
            
print(term_freq3)


[[1, 1, 0, 0], [1, 0, 1, 0], [1, 0, 0, 1]]


## Additional Challenge for the Nerds



We will learn Scikit-Learn in Module 3 which has built in the BoW feature. Try to use Scikit-Learn to generate the BoW for this challenge and check whether the output is the same as yours. You will need to do some googling to find out how to use Scikit-Learn to generate BoW.

Notes:

To install Scikit-Learn, use pip install sklearn.

Scikit-Learn removes stop words by default. You don't need to manually remove stop words.

Scikit-Learn's output has slightly different format from the output example demonstrated above. It's ok, you don't need to convert the Scikit-Learn output.

The Scikit-Learn output will look like below:



In [180]:
pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=b740daf18f82afd450470efe779f1efd725170a846515910c5e70a531ad104a0
  Stored in directory: /Users/derinkivaner/Library/Caches/pip/wheels/e4/7b/98/b6466d71b8d738a0c547008b9eb39bf8676d1ff6ca4b22af1c
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [184]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
#Fit the bag-of-words model
NEW_BOW= vectorizer.fit_transform(corpus_clean)
# Get unique words/tokens found in akk the documents. The unique words/tokens represents
#the features

print(vectorizer.get_feature_names_out())
#Associate the inides with each unique word
print(vectorizer.vocabulary_)
# Print the numerical value vector
print(NEW_BOW.toarray())

['am' 'at' 'cool' 'ironhack' 'is' 'love' 'student']
{'ironhack': 3, 'is': 4, 'cool': 2, 'am': 0, 'student': 6, 'at': 1, 'love': 5}
[[0 0 1 1 1 0 0]
 [1 1 0 1 0 0 1]
 [0 0 0 1 0 1 0]]


In [185]:
corpus_clean

['ironhack is cool', 'i am a student at ironhack', 'i love ironhack']