Import the NUMPY package under the name np.


In [13]:
import numpy as np

1. Print the NUMPY version and the configuration.



In [14]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/derinkivaner/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/derinkivaner/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/derinkivaner/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/derinkivaner/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/derinkivaner/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/derinkivaner/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/derinkivaner/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/derinkivaner/opt/anaconda3/include']
Supported


Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?



In [15]:
a=np.random.random((2,3,5))



Print a.




In [16]:
print(a)

[[[0.71018955 0.12281943 0.99257707 0.98110609 0.34200509]
  [0.60682586 0.28130253 0.43300314 0.23265259 0.36281085]
  [0.76449524 0.96012857 0.86250844 0.06432616 0.91128535]]

 [[0.58241179 0.93314705 0.46032252 0.87937692 0.55048056]
  [0.2418139  0.13961817 0.72539929 0.16251681 0.32500397]
  [0.5777678  0.40930699 0.84658506 0.4134439  0.0736527 ]]]


In [17]:
#rand: returns random float between 0 and 1

a1=np.random.rand(2,3,5)
print(a1)

[[[0.58956921 0.38170234 0.18360913 0.82004621 0.31164362]
  [0.34363682 0.38466937 0.37382518 0.50091483 0.47835108]
  [0.47125333 0.92839533 0.53836725 0.86605427 0.25154596]]

 [[0.48048323 0.13803529 0.29049579 0.03374611 0.64596574]
  [0.92200269 0.54015018 0.6675315  0.26311681 0.17475826]
  [0.3654988  0.62948271 0.58217771 0.73825434 0.38006871]]]


In [18]:
#randn 3 dimensional array of random values

a3=np.random.rand(2,3,5)
print(a3)

[[[0.67391929 0.16000719 0.28985976 0.46210786 0.01529802]
  [0.87700801 0.80147898 0.44267627 0.64491589 0.51792964]
  [0.20741986 0.34128191 0.21666504 0.0892588  0.60033766]]

 [[0.91143583 0.05285059 0.48997135 0.14310569 0.99444966]
  [0.24504918 0.52754149 0.52805444 0.55782153 0.91504692]
  [0.61369966 0.97706114 0.42919822 0.10328351 0.72173741]]]



Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



In [19]:
b=np.ones((5,2,3))


 Print b.


In [20]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]




Do a and b have the same size? How do you prove that in Python code?




In [21]:
np.size(a)==np.size(b)

True


Are you able to add a and b? Why or why not?




In [22]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### CANNOT BE ADDES UNLESS RESHAPED

In [23]:
np.add(a,b.reshape(2,3,5))

array([[[1.71018955, 1.12281943, 1.99257707, 1.98110609, 1.34200509],
        [1.60682586, 1.28130253, 1.43300314, 1.23265259, 1.36281085],
        [1.76449524, 1.96012857, 1.86250844, 1.06432616, 1.91128535]],

       [[1.58241179, 1.93314705, 1.46032252, 1.87937692, 1.55048056],
        [1.2418139 , 1.13961817, 1.72539929, 1.16251681, 1.32500397],
        [1.5777678 , 1.40930699, 1.84658506, 1.4134439 , 1.0736527 ]]])

Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".




In [24]:
c=np.transpose(b, (1,2,0))

In [25]:
c.shape

(2, 3, 5)


Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?




In [26]:
d=np.add(a,c)
print(d)

[[[1.71018955 1.12281943 1.99257707 1.98110609 1.34200509]
  [1.60682586 1.28130253 1.43300314 1.23265259 1.36281085]
  [1.76449524 1.96012857 1.86250844 1.06432616 1.91128535]]

 [[1.58241179 1.93314705 1.46032252 1.87937692 1.55048056]
  [1.2418139  1.13961817 1.72539929 1.16251681 1.32500397]
  [1.5777678  1.40930699 1.84658506 1.4134439  1.0736527 ]]]


### IT WORKS BECAUSE THEY ARE THE SAME SHAPE NOW


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.




In [27]:
print(a)
print(d)

[[[0.71018955 0.12281943 0.99257707 0.98110609 0.34200509]
  [0.60682586 0.28130253 0.43300314 0.23265259 0.36281085]
  [0.76449524 0.96012857 0.86250844 0.06432616 0.91128535]]

 [[0.58241179 0.93314705 0.46032252 0.87937692 0.55048056]
  [0.2418139  0.13961817 0.72539929 0.16251681 0.32500397]
  [0.5777678  0.40930699 0.84658506 0.4134439  0.0736527 ]]]
[[[1.71018955 1.12281943 1.99257707 1.98110609 1.34200509]
  [1.60682586 1.28130253 1.43300314 1.23265259 1.36281085]
  [1.76449524 1.96012857 1.86250844 1.06432616 1.91128535]]

 [[1.58241179 1.93314705 1.46032252 1.87937692 1.55048056]
  [1.2418139  1.13961817 1.72539929 1.16251681 1.32500397]
  [1.5777678  1.40930699 1.84658506 1.4134439  1.0736527 ]]]


### The difference is that every element in the array has ben increased by one because we added  array c which contains only elements = 1. So its the addition of each element. 



12. Multiply a and c. Assign the result to e.



In [28]:
e=np.multiply(a,c)
print(e)

[[[0.71018955 0.12281943 0.99257707 0.98110609 0.34200509]
  [0.60682586 0.28130253 0.43300314 0.23265259 0.36281085]
  [0.76449524 0.96012857 0.86250844 0.06432616 0.91128535]]

 [[0.58241179 0.93314705 0.46032252 0.87937692 0.55048056]
  [0.2418139  0.13961817 0.72539929 0.16251681 0.32500397]
  [0.5777678  0.40930699 0.84658506 0.4134439  0.0736527 ]]]




13. Does e equal to a? Why or why not?




### e equals a because c contains only elements equal to 1. Every element in a is being multiplied by 1 to result in e.


14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"




In [29]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.992577073311422
1.0643261616718762
1.5316294460699935




15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [30]:
f=np.empty((2,3,5))


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [31]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if (d_mean>d[i][j][k]>d_min):
                f[i][j][k]=25
            elif (d_max>d[i][j][k]>d_mean):
                f[i][j][k]=75
            elif (d[i][j][k]==d_mean):
                f[i][j][k]=50
            elif (d[i][j][k]==d_max):
                f[i][j][k]=100
            else:
                f[i][j][k]=0
        
print(f)

[[[ 75.  25. 100.  75.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.   0.  75.]]

 [[ 75.  75.  25.  75.  75.]
  [ 25.  25.  75.  25.  25.]
  [ 75.  25.  75.  25.  25.]]]



17. Print d and f. Do you have your expected f?

### Sure. 


For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])




18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.


In [47]:
g=np.empty((2,3,5), dtype='object')

for i in range(2):
    for j in range(3):
        for k in range(5):
            if (d_mean>d[i][j][k]>d_min):
                g[i][j][k]='B'
            elif (d_max>d[i][j][k]>d_mean):
                g[i][j][k]='D'
            elif (d[i][j][k]==d_mean):
                g[i][j][k]='B'
            elif (d[i][j][k]==d_max):
                g[i][j][k]='E'
            else:
                g[i][j][k]='A'
        
print(g)


[[['D' 'B' 'E' 'D' 'B']
  ['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'D' 'A' 'D']]

 [['D' 'D' 'B' 'D' 'D']
  ['B' 'B' 'D' 'B' 'B']
  ['D' 'B' 'D' 'B' 'B']]]


# IGNORE THE REST (ANOTHER METHOD BUT USES NUMPY)

In [32]:
def converter(x):
    y=[]
    for i in x:
        for ii in i:
            for iii in ii:
                if (d_mean>iii)and(iii>d_min):
                    y.append(float(25))
                elif (d_max>iii)and(iii>d_mean):
                    y.append(float(75))
                elif (iii==d_mean):
                    y.append(float(50))
                elif (iii==d_max):
                    y.append(float(100))
                else:
                    y.append(float(0))
    return y

np.array(converter(d)).reshape(2,3,5)

                

array([[[ 75.,  25., 100.,  75.,  25.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,   0.,  75.]],

       [[ 75.,  75.,  25.,  75.,  75.],
        [ 25.,  25.,  75.,  25.,  25.],
        [ 75.,  25.,  75.,  25.,  25.]]])

In [33]:
def converter(x):
    y=[]
    for i in x:
        for ii in i:
            for iii in ii:
                if (d_mean>iii)and(iii>d_min):
                    y.append('B')
                elif (d_max>iii)and(iii>d_mean):
                    y.append('D')
                elif (iii==d_mean):
                    y.append('C')
                elif (iii==d_max):
                    y.append('E')
                else:
                    y.append('A')
    return y

np.array(converter(d)).reshape(2,3,5)

array([[['D', 'B', 'E', 'D', 'B'],
        ['D', 'B', 'B', 'B', 'B'],
        ['D', 'D', 'D', 'A', 'D']],

       [['D', 'D', 'B', 'D', 'D'],
        ['B', 'B', 'D', 'B', 'B'],
        ['D', 'B', 'D', 'B', 'B']]], dtype='<U1')